version: '3.8'
services:
  soap:
    build:
      context: ./SOAPService
      dockerfile: Dockerfile  # Adjust if the Dockerfile has a different name or location
    ports:
      - "8001:80"

  rest:
    build:
      context: ./apiws/RESTApi
      dockerfile: Dockerfile
    ports:
      - "8002:80"

  grpc:
    build:
      context: ./gRPCProject/GrpcService
      dockerfile: Dockerfile
    ports:
      - "8003:80"
