version: '3.8'
services:
  soap:
    build: ./SOAPService
    ports:
      - "8001:80"

  rest:
    build: ./apiws
    ports:
      - "8002:80"

  grpc:
    build: ./gRPCProject
    ports:
      - "8003:80"